OPTION_LABEL_IDS = '//*[@id="parametro-nome"]'
DEPUTADO_NOME = '//*[@id="nomedeputado"]'
DEPUTADO_PRESENCA = '//*[@id="atuacao-section"]/div[2]/ul[2]/li[1]/dl/dd[1]'
DEPUTADO_AUSENCIA_JUST = '//*[@id="atuacao-section"]/div[2]/ul[2]/li[1]/dl/dd[2]'
DEPUTADO_AUSENCIA_NAO_JUST = '//*[@id="atuacao-section"]/div[2]/ul[2]/li[1]/dl/dd[3]'